#!/bin/bash
cat > .env.local <<EOF
SLS_AWS_BUCKET_NAME=$SLS_AWS_BUCKET_NAME
SLS_AWS_BUCKET_REGION=$AWS_REGION
NEXT_PUBLIC_GRAPHQL_URL=$NEXT_PUBLIC_GRAPHQL_URL
NEXT_PUBLIC_API_ENDPOINT=$NEXT_PUBLIC_API_ENDPOINT
EOF
