Description: 'This template creates resources for deployment with serverless-nextjs'

Resources:
  ServerlessStateBucket:
    Type: AWS::S3::Bucket

  # LambdaEdgeBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: onspread-blog-lambda-edge-bucket

  # LambdaEdgeDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   DependsOn: LambdaEdgeBucket
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #         - DomainName: onspread-blog-lambda-edge-bucket.s3.amazonaws.com
  #           Id: onspread-blog-lambda-edge-bucket
  #           S3OriginConfig:
  #             OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
  #       Enabled: true
  #       Comment: Some comment
  #       DefaultRootObject: index.html
  #       Logging:
  #         IncludeCookies: false
  #         Bucket: mylogs.s3.amazonaws.com
  #         Prefix: myprefix
  #       Aliases:
  #         - blog.onspread.com
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #           - DELETE
  #           - GET
  #           - HEAD
  #           - OPTIONS
  #           - PATCH
  #           - POST
  #           - PUT
  #         TargetOriginId: onspread-blog-lambda-edge-bucket
  #         ForwardedValues:
  #           QueryString: false
  #           Cookies:
  #             Forward: none
  #         TrustedSigners:
  #           - 1234567890EX
  #           - 1234567891EX
  #         ViewerProtocolPolicy: allow-all
  #       PriceClass: PriceClass_200
  #       Restrictions:
  #         GeoRestriction:
  #           RestrictionType: whitelist
  #           Locations:
  #             - AQ
  #             - CV
  #       ViewerCertificate:
  #         CloudFrontDefaultCertificate: true
